### ISSUE TITLE
Settings Falsely Stuck in "Enable 8Vim"

### ISSUE THREAD

**Issue by mentalisttraceur** [8VIM/8VIM#415] opened 2023-10-27 12:57 UTC
**Describe the bug**
8vim settings is stuck thinking that it's not enabled, when it is.

No amount of toggling is getting it unstuck.

**To Reproduce**
No idea.

This started a couple updates back I think. I mostly use GBoard and only switch back to 8vim to see if it works as well as the vision in my head yet (it's gradually getting there).

**Expected behavior**
If 8vim is enabled in the system settings, this doesn't happen.

**Screenshots**
8vim:
![Screenshot_20231027-124828](https://github.com/8VIM/8VIM/assets/6531708/683cb180-9680-471e-acc6-7bf8270b112a)

Split-screen Settings+8vim:

![Screenshot_20231027-130039](https://github.com/8VIM/8VIM/assets/6531708/6de2eabb-6d07-4eaa-becd-e3f8a99d8374)

**Desktop (please complete the following information):**
... how is this relevant?

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 14 (but I think I first saw this before the 14 update)
 - Browser: ... how is this relevant?
 - Version: ... of what? 8vim? Latest on FDroid as of this time, plus one or more previous ones.

**Comment by mentalisttraceur** [comment] 2023-10-27 13:06
Reinstalling, surprisingly, didn't fix it.

**Comment by MaethorNaur** [comment] 2023-10-27 14:57
I'll have look at it

**Comment by lividhen** [comment] 2023-10-27 17:34
Also experiencing this.

**Comment by MaethorNaur** [comment] 2023-10-27 20:16
I've been trying to reproduce the bug but so far couldn't (even with a pixel 5 emulator on android 14). On my physical devices, I didn't encounter that issue.

@mentalisttraceur So after clicking on `Open System settings`, enabling the keyboard and being redirected to the setup the next step is still disabled and the previous one is half shown?
What if you force close 8Vim, does it stay the same?
Did that stop working on the version after it was introduced (v0.15.0) or v0.16.x versions?
Did you try on the split-screen only in split-screen?

@lividhen Are you also on android 14?

I'm going to create a new patch version, but that time with logging with an option to export it, so I could have a better understanding (something is probably crashing in the background and not being logged)

**Comment by lividhen** [comment] 2023-10-27 21:14
Yes I am.

**Comment by MaethorNaur** [comment] 2023-10-27 21:25
@lividhen also on a pixel? or is it a beta version?
Unfortunately, I don't own a phone with Android 14, I should have access to one tomorrow and check the logs.

**Comment by mentalisttraceur** [comment] 2023-10-28 03:36
> and being redirected to the setup the next step

There's no redirect. I toggle the keyboard on but the view stays on the keyboard settings activity.

(I did think that in itself felt weird, felt like I remembered it normally redirecting back automatically.)

**Comment by MaethorNaur** [comment] 2023-10-28 03:41
> There's no redirect. I toggle the keyboard on but the view stays on the keyboard settings activity.
> 
> (I did think that in itself felt weird, felt like I remembered it normally redirecting back automatically.)

Right, do you remember from which version that started to happen (since the introduction of the setup process)?

**Comment by mentalisttraceur** [comment] 2023-10-28 03:47
Can't remember, sorry - for several months now I've only opened 8vim when there were new f-droid updates for it, and even then maybe not every time.

To the best of my recollection, within the last two updates is when I first noticed it, but that could be wrong too.

**Comment by MaethorNaur** [comment] 2023-10-28 03:54
> Can't remember, sorry - for several months now I've only opened 8vim when there were new f-droid updates for it, and even then maybe not every time.
> 
> To the best of my recollection, within the last two updates is when I first noticed it, but that could be wrong too.

I see. there's definitely an issue in the background and the app might have been crashing silently.
Did you always use android 14?

**Comment by mentalisttraceur** [comment] 2023-10-28 04:03
Only got upgrade to Android 14 fairly recently. 2-3 weeks ago I believe.

**Comment by lividhen** [comment] 2023-10-28 19:01
> @lividhen also on a pixel? or is it a beta version? Unfortunately, I don't own a phone with Android 14, I should have access to one tomorrow and check the logs.

On the oneui 6 beta.

**Comment by mtivi** [comment] 2023-10-29 00:36
I also am experiencing the issue on Pixel 8.

I am however able to use the keyboard. Settings are accessible via in-keyboad settings button.

![Screenshot_20231028-203524.png](https://github.com/8VIM/8VIM/assets/60046004/4353be40-94fd-4f40-b0a5-4bb40d8f420d)

Just in case this helps in debugging.

**Comment by mentalisttraceur** [comment] 2023-10-29 01:01
Same, thanks for remembering to mention this:

> able to use the keyboard. Settings are accessible via in-keyboad settings button.

The thing that made me finally report this issue was that I toggled off that side-bar in the settings, then couldn't get back into the settings, haha (reinstalling reset the settings and made the bar and thus the settings accessible again... I think clearing app data would too).

**Comment by MaethorNaur** [comment] 2023-10-29 01:07
Thank you for reporting the issue. I think I found the root cause

**Comment by MaethorNaur** [comment] 2023-11-18 21:39
Hi, sorry for the delay. Could you tell me if the bug is fixed with: https://github.com/8VIM/8VIM/releases/tag/v0.16.3-rc.1 ?

**Comment by mentalisttraceur** [comment] 2023-11-18 22:50
Yep, works for me!

**Closed as completed** 2023-11-18 22:54 UTC

**Comment by MaethorNaur** [comment] 2023-11-18 23:07
Available on the new release: https://github.com/8VIM/8VIM/releases/tag/v0.16.3
For F-droid users the release should be available in around 3-5 days
