### ISSUE TITLE
Add option to change & disable vibration

### ISSUE THREAD

**Issue by m-rey** [8VIM/8VIM#92] opened 2020-11-11 18:23 UTC
It would be great if users could customize when the keyboard vibrates. For example, it would be nice if users could configure the keyboard to vibrate when sliding over the section dividers. That way, you could instinctively know when you've glided enough with your finger.

However, while I understand that vibration can be useful for some, it can be annoying for others. Therefore, it would be awesome if vibration could also be completely deactivated.

**Comment by sultanahamer** [comment] 2020-11-16 19:42
I am looking forward to this. Meanwhile, I have checked out iteration-5 and disabled the haptic feedback and installed debug version for now.

I am developer of OpenContacts an android app that you can find on f-droid. Do let me know in case you need help in fixing this. Also, I am thinking that we might have to create a typing tutor kind of thing for this keyboard for people to practice and get faster sooner.

**Comment by flide** [comment] 2020-12-03 13:23
Closing this as duplicate of #71

**Closed as completed by flide** 2020-12-03 13:23 UTC
Labels: enhancement
