### ISSUE TITLE
[Bug] Sidebar left/right setting doesn't seem to work

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#50] opened 2020-10-17 19:01 UTC
This still puzzles me: The Sidebar-Left / Sidebar-Right buttons in 8Vim don't seem to do anything. I feel like they used to, but now it seems somewhat random whether they do something.

I suggest, that upon button-press, the keyboard should IMMEDIATELY be restructured.

If other settings have a similar delayed effect, also make them immediately effect the keyboard.

**Comment by flide** [comment] 2020-10-18 01:35
duplicate of #36

**Closed as completed** 2020-10-18 01:50 UTC
Labels: duplicate

**Comment by m-rey** [comment] 2020-11-06 08:04
As a temporary workaround until #36 is fixed, you could display a toast message when the sidebar-left or sidebar-right button is pressed. That way, users will know that something changed.
