### ISSUE TITLE
Theme the settings menu.

### ISSUE THREAD

**Issue by MinekPo1** [8VIM/8VIM#242] opened 2022-01-11 14:06 UTC
As someone used to dark mode interfaces, I am always slightly annoyed when greeted by the pure white interface of the settings menu for the app.

Perhaps reuse the colors used for theming the keyboard itself?

**Comment by flide** [comment] 2022-03-05 20:32
duplicate of #111

**Closed as completed** 2022-03-05 20:32 UTC

**Comment by MinekPo1** [comment] 2022-03-05 22:33
my bad sorry
