### ISSUE TITLE
[Bug] Closing 8Vim while using it results in odd behaviour.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#81] opened 2020-11-04 17:06 UTC
All those bugs can be removed by re-opening the keyboard and tapping somewhere or just swiping.

- Want to display fun shapes with your keyboard?
Swipe around in 8vim (having the touch trail enabled), then press back or that key that takes you to the task-manager-like-view. Make sure to press it _while you're still drawing a line_.
Reopen the keyboard and watch the nice line you drew!  :)
- Want to turn your phone into a vibrating thing? 
Perform **and hold** any action that is able to rapid-fire (backspace for example of right sector -> center), then press back or that key that takes you to the task-manager-like-view. Make sure to press it _ as you're still holding the rapid-fire-button_.
Now go play with your toy. :)
- Want to partially lock yourself out from your phone?
Go into the browser of your choice (i did it in FireFox) and type a few letters into the search-field. Press and hold the enter-button (the bottom section)
Now good luck disabling that effect again. :)

> Want to display fun shapes with your keyboard?

Btw, this is SUPER EASY to do. Just swipe from right to left sector of your keyboard. That thing should open:
![8Vim_Editing_Keyboard](https://user-images.githubusercontent.com/59611881/98142561-3ff14100-1ec8-11eb-9b37-953855342925.jpeg)
Now just click the icon on the bottom left to get back to the keyboard, and volla. A pretty color-trail.  :)

**Comment by flide** [comment] 2020-11-04 17:17
second and third one are logged as bug #58

**Comment by Glitchy-Tozier** [comment] 2020-11-04 17:19
Ok, should I delete them from the text then?

**Comment by flide** [comment] 2020-11-04 17:29
By the way, that funky looking thing is something i call 'selection keypad'. It exits to emutale visual mode as used in vim. 

The way to get to it is pressing that '4 arrow' symbol on the sidebar. 

When you swipe from right to center and hold, the gesture effectively starts selecting/highlighting text backward from the curson position. As you let go of the hold, the selection keypad opens up to fine tune your selection and allow for basic things with the selection like cut, copy, paste etc. 

More features are planned for selection keypad ... someday...

By the way, selection keypad is one of the most useful feature in the keyboard, try using it.

**Comment by flide** [comment] 2020-11-04 17:53
> Ok, should I delete them from the text then?
> 

no need

**Comment by flide** [comment] 2020-12-03 05:14
@Glitchy-Tozier, Is it okay if I close this as duplicate of #58 ?

**Comment by Glitchy-Tozier** [comment] 2020-12-03 08:21
> @Glitchy-Tozier, Is it okay if I close this as duplicate of #58 ?

I'm not 100% sure but I guess so.

**Comment by flide** [comment] 2020-12-03 14:15
@Glitchy-Tozier If you feel we are missing out on any bug by closing this, please raise it as a new issue. Closing this as duplicate of #58

**Closed as completed by flide** 2020-12-03 14:15 UTC
